INSERT INTO test.user (name, age, isAdmin) VALUES ('User1', '23', 1);
INSERT INTO test.user (name, age, isAdmin) VALUES ('Agent Smith', '1024', 1);
INSERT INTO test.user (name, age, isAdmin) VALUES ('Mr. Anderson', '31', 0);
INSERT INTO test.user (name, age, isAdmin) VALUES ('Optimus Prime', '256', 0);
INSERT INTO test.user (name, age, isAdmin) VALUES ('Bilbo Baggins', '111', 1);
INSERT INTO test.user (name, age, isAdmin) VALUES ('Gandalf', '10876', 1);
INSERT INTO test.user (name, age, isAdmin) VALUES ('Korvin', '75', 0);
INSERT INTO test.user (name, age, isAdmin) VALUES ('Germiona Granger', '18', 0);
INSERT INTO test.user (name, age, isAdmin) VALUES ('Tom Marvolo Reddle', '18', 1);
INSERT INTO test.user (name, age, isAdmin) VALUES ('James Hetfield', '54', 0);
INSERT INTO test.user (name, age, isAdmin) VALUES ('User2', '34', 1);
INSERT INTO test.user (name, age, isAdmin) VALUES ('Sherlok Holmes', '42', 1);
INSERT INTO test.user (name, age, isAdmin) VALUES ('John Watson', '33', 0);
INSERT INTO test.user (name, age, isAdmin) VALUES ('Robert Baratheon', '51', 0);
INSERT INTO test.user (name, age, isAdmin) VALUES ('Roland Diskein', '97', 1);
INSERT INTO test.user (name, age, isAdmin) VALUES ('Odetta Holmes', '24', 1);
INSERT INTO test.user (name, age, isAdmin) VALUES ('Oberin Martell', '39', 0);
INSERT INTO test.user (name, age, isAdmin) VALUES ('Albus Dumbledor', '87', 0);
INSERT INTO test.user (name, age, isAdmin) VALUES ('Ganelon', '42', 1);
INSERT INTO test.user (name, age, isAdmin) VALUES ('Dent Arthur Dent', '29', 0);